from typing import Any
import numpy as np

from helpers.huff2mat import huff2mat
from helpers.jpeg2im import jpeg2im


def _get_distinct_block(mat: Any, m: Any, col: Any, rows: Any):
    """_get_distinct_block."""
    # MATLAB col index is 1-based; here col is 0-based.
    x = 1 + (m * col) % rows
    y = 1 + m * ((col * m) // rows)
    blk = mat[x - 1 : x - 1 + m, y - 1 : y - 1 + m]
    return blk, x, y


def _blocks_to_cols_distinct(mat: Any, m: Any):
    """_blocks_to_cols_distinct."""
    rows, cols = mat.shape
    nb = (rows // m) * (cols // m)
    out = np.zeros((m * m, nb), dtype=float)
    for col in range(nb):
        blk, _, _ = _get_distinct_block(mat, m, col, rows)
        out[:, col] = blk.reshape(-1, order="F")
    return out


def _cols_to_blocks_distinct(cols_data: Any, out_shape: Any, m: Any):
    """_cols_to_blocks_distinct."""
    rows, cols = out_shape
    nb = (rows // m) * (cols // m)
    out = np.zeros((rows, cols), dtype=float)
    for col in range(nb):
        _, x, y = _get_distinct_block(out, m, col, rows)
        out[x - 1 : x - 1 + m, y - 1 : y - 1 + m] = cols_data[:, col].reshape(
            (m, m), order="F"
        )
    return out


def _write_multipage_tiff(path: Any, frames_uint8: Any):
    """_write_multipage_tiff."""
    # Prefer tifffile for explicit no-compression write.
    try:
        import tifffile

        stack = np.stack(frames_uint8, axis=0)
        tifffile.imwrite(path, stack, compression=None)
        return
    except Exception:
        pass

    # Fallback: PIL append save.
    try:
        from PIL import Image

        ims = [Image.fromarray(fr) for fr in frames_uint8]
        ims[0].save(
            path,
            save_all=True,
            append_images=ims[1:],
            compression="raw",
        )
        return
    except Exception as exc:
        raise RuntimeError(
            "Unable to write multi-frame TIFF. Install tifffile or Pillow."
        ) from exc


def cv2tifs(y: Any, f: Any):
    """
    Decode a TIFS2CV compressed sequence and write a multi-frame TIFF.
    MATLAB-faithful translation of DIPUM cv2tifs.m.

    Parameters
    ----------
    y : dict
        Coding structure generated by tifs2cv.
    f : str
        Output multi-frame TIFF filename.

    Returns
    -------
    list[np.ndarray]
        Reconstructed uint8 frames (also written to disk).
    """
    fcnt = int(np.asarray(y["frames"]).reshape(-1)[0])
    m = int(np.asarray(y["blksz"]).reshape(-1)[0])
    q = int(np.asarray(y["quality"]).reshape(-1)[0])

    # Reconstruct first frame.
    if q == 0:
        r = huff2mat(y["video"][0]).astype(float)
    else:
        r = jpeg2im(y["video"][0]).astype(float)

    fsz = r.shape
    mvsz = (fsz[0] // m, fsz[1] // m, 2, fcnt)

    # MATLAB: mv = int16(huff2mat(y.motion)); mv = reshape(mv,mvsz);
    mv = np.int16(np.round(huff2mat(y["motion"])))
    mv = np.asarray(mv).reshape(mvsz, order="F")

    frames = [np.uint8(np.clip(np.round(r), 0, 255))]

    # Remaining frames.
    for i in range(1, fcnt):
        if q == 0:
            pe = huff2mat(y["video"][i]).astype(float)
        else:
            pe = jpeg2im(y["video"][i]).astype(float) - 255.0

        peC = _blocks_to_cols_distinct(pe, m)

        for col in range(peC.shape[1]):
            u = 1 + (m * col) % fsz[0]
            v = 1 + m * ((col * m) // fsz[0])

            bi = (u - 1) // m
            bj = (v - 1) // m
            rx = int(u - mv[bi, bj, 0, i])
            ry = int(v - mv[bi, bj, 1, i])

            subimage = r[rx - 1 : rx - 1 + m, ry - 1 : ry - 1 + m]
            peC[:, col] = subimage.reshape(-1, order="F") - peC[:, col]

        r = _cols_to_blocks_distinct(np.uint16(peC).astype(float), fsz, m)
        frames.append(np.uint8(np.clip(np.round(r), 0, 255)))

    _write_multipage_tiff(f, frames)
    return frames
