from typing import Any
import numpy as np


def houghpeaks(H: Any, numpeaks: Any = 1, threshold: Any = None, nhood: Any = None):
    """
    Detect peaks in Hough transform.

    Parameters:
        H: Hough transform accumulator (2D array).
        numpeaks: Max number of peaks to find.
        threshold: Threshold for peaks. Default 0.5 * max(H).
        nhood: Size of suppression neighborhood [M, N]. Default derived from size(H)/50.

    Returns:
        r, c: Row and column indices of peaks (rho_idx, theta_idx).
    """

    if threshold is None:
        threshold = 0.5 * np.max(H)

    if nhood is None:
        # nhood = size(h)/50
        # Make sure odd.
        # size(H) is (rows, cols) -> (rho_len, theta_len)
        nhood = np.array(H.shape) / 50.0
        nhood = np.maximum(2 * np.ceil(nhood / 2) + 1, 1).astype(int)

    M, N = H.shape
    H_new = H.copy()

    peaks = []

    for _ in range(numpeaks):
        # Find max
        flat_idx = np.argmax(H_new)
        p, q = np.unravel_index(flat_idx, H_new.shape)

        if H_new[p, q] >= threshold:
            peaks.append([p, q])

            # Suppress neighborhood
            # p1 = p - (nhood(1) - 1)/2; similar logic
            p_start = p - (nhood[0] - 1) // 2
            p_end = p + (nhood[0] - 1) // 2

            q_start = q - (nhood[1] - 1) // 2
            q_end = q + (nhood[1] - 1) // 2

            # Create grid of indices
            # Handling boundaries and wrap around for theta
            # MATLAB code:
            # theta_too_low = find(qq < 1);
            # qq(theta_too_low) = size(h, 2) + qq(theta_too_low);
            # pp(theta_too_low) = size(h, 1) - pp(theta_too_low) + 1;

            # Python indices 0-based.
            # p range
            pp_grid, qq_grid = np.meshgrid(
                np.arange(p_start, p_end + 1),
                np.arange(q_start, q_end + 1),
                indexing="ij",
            )

            pp = pp_grid.flatten()
            qq = qq_grid.flatten()

            # Rho bounds (throw away out of bounds)
            valid_rho = (pp >= 0) & (pp < M)
            pp = pp[valid_rho]
            qq = qq[valid_rho]

            # Theta bounds (wrap around with antisymmetry)
            # if qq < 0:
            #   qq = N + qq
            #   pp = M - pp - 1 ? (MATLAB: size(h,1) - pp + 1 => M - (pp_matlab) + 1. 0-based: M-1 - pp)
            #   Wait, MATLAB 1-based:
            #   pp(new) = M - pp(old) + 1.
            #   0-based: (M-1) - pp
            #   Let's verify:
            #   MATLAB M=100. pp=1 -> M-1+1 = 100. pp=100 -> 1.
            #   Python M=100. pp=0 -> 99. pp=99 -> 0.
            #   Formula: M - 1 - pp

            # Handle too low
            too_low = qq < 0
            if np.any(too_low):
                qq[too_low] += N
                pp[too_low] = M - 1 - pp[too_low]

            # Handle too high
            too_high = qq >= N
            if np.any(too_high):
                qq[too_high] -= N
                pp[too_high] = M - 1 - pp[too_high]

            # Filter again for bad rho generated by reflection?
            # Reflection flips rho. If rho was near bounds, reflection keeps it in bounds (0..M-1).
            # But the original suppression window could go outside rho bounds, which we discarded.
            # The reflection applies to theta out of bounds.
            # If we reflect, we need to ensure new pp is valid.
            # M-1 - pp. Since original pp was in [0, M-1] (checked by valid_rho), new pp is also in [0, M-1].

            # Zero out
            # Need unique indices to avoid assigning same place multiple times? Doesn't matter for 0 assignment.
            # Ensure indices valid
            valid = (pp >= 0) & (pp < M) & (qq >= 0) & (qq < N)
            H_new[pp[valid], qq[valid]] = 0

        else:
            break

    # Return r, c lists
    if not peaks:
        return np.array([]), np.array([])

    peaks = np.array(peaks)
    return peaks[:, 0], peaks[:, 1]
