import numpy as np
from helpers.libdipum.huff2mat import huff2mat

def lpc2im4e(c):
    """
    Decompresses a 1-D lossless predictive encoded matrix.
    
    Parameters:
    -----------
    c : dict
        Structure generated by im2lpc4e containing 'coefs' and 'huffman'.
        
    Returns:
    --------
    f : numpy.ndarray
        Reconstructed matrix.
    """
    if not isinstance(c, dict) or 'coefs' not in c or 'huffman' not in c:
        raise ValueError("Input must be a valid LPC structure.")
        
    coefs = c['coefs']
    huff_struct = c['huffman']
    
    # Decode Huffman encoded prediction error
    # This gives us 'e' (error = f - round(p))
    prediction_error = huff2mat(huff_struct)
    
    # Convert prediction error back to float if reconstructed as something else?
    # huff2mat returns float (or whatever huff2mat defaults to, which is float array).
    
    # Reconstruct image
    m, n = prediction_error.shape
    
    # The reconstruction is autoregressive.
    # f(:, j) = error(:, j) + round(prediction)
    # prediction depends on previous 'order' columns.
    
    # Prepare coefs for reconstruction
    # In MATLAB: coefs = coefs(end:-1:1) (Reverse) because convolution/filter direction?
    # Let's trace im2lpc.
    # im2lpc:
    # p(x) = c1*f(x-1) + c2*f(x-2) ...
    # So if order is K, f(x) uses f(x-1)...f(x-K).
    
    # MATLAB lpc2im4e logic:
    # coefs = coefs(end:-1:1) (Reverse)
    # coefs = repmat(...)
    # f = zeros(m, n + order)
    # Loop columns j = 1 to n
    #   jj = j + order
    #   pred = sum( coefs * f(:, jj-1 : jj-order) )
    #   f(:, jj) = error(:, j) + round(pred)
    
    # The MATLAB loop iterates 1 to n.
    # It accesses f from jj-1 backwards to jj-order.
    # With coefs also reversed?
    # Original coefs: c[0] applies to f(x-1), c[1] to f(x-2).
    # If we hold `window = [f(x-1), f(x-2)...]`, then `pred = dot(coefs, window)`.
    # MATLAB creates window slicing `f(:, (jj-1):-1:(jj-order))`.
    # This slice is `[f(x-1), f(x-2) ... f(x-order)]`.
    # It multiplies by `coefs(:, order:-1:1)`.
    # Wait.
    # MATLAB code:
    # coefs = coefs(end:-1:1) (reversed once globally)
    # Inside loop: sum( coefs(:, order:-1:1) .* f_slice )
    # `coefs(:, order:-1:1)` reverses the ALREADY reversed coefs?
    # So it uses original order?
    # Let's check:
    # Global: coefs_rev = [ck, ..., c1]
    # Slice inside loop: coefs_rev(order:-1:1) -> [c1, ..., ck]
    # So it effectively uses [c1...ck] multiplied elementwise with [f(x-1)...f(x-k)].
    # This matches `p = c1*f(x-1) + ...`.
    
    # So in Python:
    # We can keep coefs as is: [c1, c2, ... ck]
    # And slice f: [f_col(j-1), f_col(j-2) ... f_col(j-k)]
    # And dot product.
    
    # Ensure coefs is float array
    coefs = np.array(coefs, dtype=float).flatten()
    order = len(coefs)
    
    # Pad f to handle boundary conditions
    # Left padding of 'order' columns with 0.
    f = np.zeros((m, n + order))
    
    # Copy error? No, error is separate.
    # We fill f column by column.
    
    # Iterate columns
    for j in range(n):
        # Current column index in padded f is j + order
        jj = j + order
        
        # Window of previous columns
        # We need columns [jj-1, jj-2, ... jj-order]
        # Slicing in numpy with step -1:
        # f[:, jj-1 : jj-order-1 : -1] -> this gives columns in order (j-1, j-2...)
        # Note: stop index is exclusive.
        
        # previous_cols shape: (m, order)
        # But wait, checking slice ranges:
        # If order=1, jj-1 is start. jj-2 is stop.
        # Slice: f[:, jj-1 : jj-2 : -1] includes jj-1.
        
        prev_cols = f[:, range(jj-1, jj-order-1, -1)]
        
        # Calculate prediction
        # partial sums: prev_cols(pixel i) dot coefs
        # coefs shape: (order,)
        # prev_cols shape: (m, order)
        # dot product along axis 1
        
        pred = np.dot(prev_cols, coefs)
        
        # Reconstruct pixel
        # f(x) = error(x) + round(pred)
        f[:, jj] = prediction_error[:, j] + np.round(pred)
        
    # Remove padding
    f_final = f[:, order:]
    
    return f_final
