from typing import Any
import numpy as np

from helpers.libdipum.huff2mat import huff2mat
from helpers.libdipum.intline import intline
from helpers.libdipum.jpeg2im import jpeg2im


def showmo(cv: Any, i: Any):
    """
    Display the motion vectors of frame i from a TIFS2CV coding structure.

    Parameters
    ----------
    cv : dict
        Structure generated by tifs2cv.
    i : int
        1-based frame index (MATLAB style).

    Returns
    -------
    np.ndarray
        Motion-vector visualization image (uint8).
    """
    frms = int(np.asarray(cv["frames"]).reshape(-1)[0])
    m = int(np.asarray(cv["blksz"]).reshape(-1)[0])
    q = int(np.asarray(cv["quality"]).reshape(-1)[0])

    if i < 1 or i > frms:
        raise ValueError(f"Frame index i must be in [1, {frms}].")

    if q == 0:
        ref = huff2mat(cv["video"][0]).astype(float)
    else:
        ref = jpeg2im(cv["video"][0]).astype(float)

    fsz = ref.shape
    mvsz = (fsz[0] // m, fsz[1] // m, 2, frms)

    mv = np.int16(np.round(huff2mat(cv["motion"])))
    mv = np.asarray(mv).reshape(mvsz, order="F")

    v = np.zeros(fsz, dtype=np.uint8) + 128

    # Create motion vector image.
    nb = mvsz[0] * mvsz[1]
    fi = i - 1  # Python index for MATLAB frame i.
    for j in range(1, nb + 1):
        x1 = 1 + (m * (j - 1)) % fsz[0]
        y1 = 1 + m * (((j - 1) * m) // fsz[0])

        bi = 1 + ((x1 - 1) // m)
        bj = 1 + ((y1 - 1) // m)

        x2 = x1 - int(mv[bi - 1, bj - 1, 0, fi])
        y2 = y1 - int(mv[bi - 1, bj - 1, 1, fi])

        x, y = intline(x1, float(x2), y1, float(y2))

        if len(x) > 1:
            rr = x[:-1] - 1
            cc = y[:-1] - 1
            good = (rr >= 0) & (rr < fsz[0]) & (cc >= 0) & (cc < fsz[1])
            v[rr[good], cc[good]] = 255

        rr = x[-1] - 1
        cc = y[-1] - 1
        if (0 <= rr < fsz[0]) and (0 <= cc < fsz[1]):
            v[rr, cc] = 0

    return v
